最終結果で全ての順位が出るようにした
bamboooo-dev/himo-client pull request #5
Opened 2021-07-04 15:05 UTC by MONAKA0721

2021-07-04 15:06 UTC, MONAKA0721 commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +    switch (this.results.Length)
プレイヤーの人数によって表示したい順番が結構バラバラやったので全通り書いてしまった

2021-07-04 15:06 UTC, MONAKA0721 commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +  private IEnumerator ShowPlace(float waitTime, int place, int maxPlace)
`waitTime` 秒待って `place` 位を表示するための関数

2021-07-04 15:07 UTC, MONAKA0721 commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +    y = 450 - (place + 1) * 900 / (maxPlace + 1);
ここで人数によって表示する位置を替えてる

2021-07-04 15:07 UTC, MONAKA0721 commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +    _place.transform.Find("PlaceImage").GetComponent<Image>().sprite = placeSprites[place];
ここで順位の画像(1,2,3,...ビリetc)を替えてる

2021-07-04 15:14 UTC, yamagai requested changes
とりあえず気になったとこ

2021-07-04 15:14 UTC, yamagai commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +        StartCoroutine(ShowPlace(6.0f, 5, 6));
これ四位以下全部と一位が同じタイミングで出るよな？
ビリと一位だけが同時に出るようにしたい

2021-07-04 15:14 UTC, yamagai commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +        StartCoroutine(ShowPlace(6.0f, 4, 5));
ここもビリと一位だけが同時に出るようにしたい

2021-07-04 15:16 UTC, MONAKA0721 commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +        StartCoroutine(ShowPlace(6.0f, 5, 6));
おー、なるほど
4位以下はいつ出すのが良いと思う？

2021-07-04 15:28 UTC, yamagai commented on Assets/Scripts/15_FinalResult/FinalResultManager.cs
> +        StartCoroutine(ShowPlace(6.0f, 5, 6));
ビリの一個上から順にどんどん上位を出していって、最後にビリと1位が出るのがいいな

5人プレイやと、4位→3位→2位→1位とビリ
6人プレイやと、5位→4位→3位→2位→1位とビリ

2021-07-05 13:17 UTC, MONAKA0721 commented
@yamagai 

Uploading 画面収録 2021-07-05 22.15.48.mov…

これでいいかな？

2021-07-05 13:54 UTC, yamagai commented
Uploading 画面収録 2021-07-05 22.15.48.mov…

が文字のままになっているな

2021-07-05 13:55 UTC, MONAKA0721 commented
途中でコメント送信したらあかんのか

2021-07-05 13:56 UTC, MONAKA0721 commented
https://user-images.githubusercontent.com/32859963/124482373-2bad6d00-dde4-11eb-9e44-46a46e63179e.mov

2021-07-05 14:02 UTC, yamagai commented
良いと思います

文字でかい問題地味に気になっているのでついでに対応してくれたりすると嬉しいかもしれない 👁️ 
![スクリーンショット 2021-07-05 23 00 30](https://user-images.githubusercontent.com/48216243/124483010-daea4400-dde4-11eb-956c-6f98a9086dd1.png)
![スクリーンショット 2021-07-05 23 01 12](https://user-images.githubusercontent.com/48216243/124483068-e76e9c80-dde4-11eb-959a-4dab649ae406.png)

2021-07-05 14:10 UTC, MONAKA0721 commented
この画面だけ？

2021-07-05 14:13 UTC, yamagai commented
ここもかな
![スクリーンショット 2021-07-05 23 12 26](https://user-images.githubusercontent.com/48216243/124484531-79c37000-dde6-11eb-80b8-af4ff318d572.png)

ここまでの4画面でいいと思います

2021-07-05 15:33 UTC, MONAKA0721 commented
<img width="775" alt="スクリーンショット 2021-07-05 23 18 28" src="https://user-images.githubusercontent.com/32859963/124494325-aaf56d80-ddf1-11eb-87f0-6cc7a986dea2.png">

<img width="775" alt="スクリーンショット 2021-07-06 0 24 08" src="https://user-images.githubusercontent.com/32859963/124494334-ae88f480-ddf1-11eb-8acc-c97e3e261699.png">
<img width="775" alt="スクリーンショット 2021-07-06 0 28 48" src="https://user-images.githubusercontent.com/32859963/124494337-af218b00-ddf1-11eb-929c-75eb5313fcdf.png">
<img width="775" alt="スクリーンショット 2021-07-06 0 31 14" src="https://user-images.githubusercontent.com/32859963/124494340-afba2180-ddf1-11eb-8aa4-123b51a230db.png">

@yamagai 
修正した
結果発表の画面は調整済み

2021-07-05 15:42 UTC, yamagai approved these changes
サンクス！！

LGTM である

2021-07-05 15:52 UTC, merged